version: '3.8'
services:
  Sample:
    image: sample-prod-i
    build:
      dockerfile: Dockerfile.prod
    container_name: sample-prod-container_name
    ports:
      - "8080:80"
    environment:
      - NODE_ENV=production
